ktor:
  environment: local
  application:
    modules:
      - no.nav.tsm.ApplicationKt.module
  deployment:
    port: 8080
  database:
    dbUser: $DB_USERNAME
    dbPassword: $DB_PASSWORD
    dbHost: $DB_HOST
    dbPort: $DB_PORT
    dbName: $DB_DATABASE
  kafka:
    config:
      bootstrap.servers: $KAFKA_BROKERS
      security.protocol: "SSL"
      ssl.truststore.location: $KAFKA_TRUSTSTORE_PATH
      ssl.truststore.password: $KAFKA_CREDSTORE_PASSWORD
      ssl.truststore.type: "jks"
      ssl.keystore.location: $KAFKA_KEYSTORE_PATH
      ssl.keystore.password: $KAFKA_CREDSTORE_PASSWORD
      ssl.keystore.type: "PKCS12"
register:
  db:
    connectionName: $REGISTER_DB_CONNECTION_NAME
    username: $REGISTER_DB_USERNAME
    password: $REGISTER_DB_PASSWORD
    name: smregister
