ktor:
  environment: local
  application:
    modules:
      - no.nav.tsm.ApplicationKt.module
  deployment:
    port: 8080
  database:
    dbUser: $DB_USERNAME
    dbPassword: $DB_PASSWORD
    dbHost: $DB_HOST
    dbPort: $DB_PORT
    dbName: $DB_DATABASE
  smregister:
    database:
        dbUser: $DB_TSM_MIGRATOR_USERNAME
        dbPassword: $DB_TSM_MIGRATOR_PASSWORD
        dbHost: $DB_TSM_MIGRATOR_HOST
        dbPort: $DB_TSM_MIGRATOR_PORT
        dbName: $DB_TSM_MIGRATOR_DATABASE
