apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: migrator
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  image: {{ image }}
  replicas:
    min: 1
    max: 10
    scalingStrategy:
      cpu:
        thresholdPercentage: 90
      kafka:
        consumerGroup: sykmelding-reformat-consumer
        threshold: 50
        topic: tsm.teamsykmelding-sykmeldinger
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: tsm-pdl-cache
  envFrom:
    - secret: tsm-migrator-smregister-db

