apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: migrator
  namespace: tsm
  labels:
    team: tsm
    system: mottak
spec:
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: db-custom-2-5120
        databases:
          - name: migrator
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: false
        diskType: SSD
        insights:
          enabled: true
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
        pointInTimeRecovery: true
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: 10Gi
    requests:
      cpu: 50m
      memory: 512Mi
  secureLogs:
    enabled: true
  kafka:
    pool: nav-prod

