apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tsm-migrator-register-db
  namespace: tsm
  labels:
    team: tsm
    system: mottak

spec:
  egress:
    - to:
        - ipBlock:
            cidr: 35.228.57.214/32
  podSelector:
    matchLabels:
      app: migrator
  policyTypes:
    - Egress
