name: Deploy networkpolicy to dev
on:
  push:
    branches:
      - '**'
    paths:
      - 'nais/network-policy-dev.yaml'
      - '.github/workflows/networkpolicy-dev.yaml'

jobs:
  deploy-to-dev:
    name: Networkpolicy to dev-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy policy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais/network-policy-dev.yaml
